stages:
  - env-creation
  - prepare-${{values.aws_environment_name}}-stage
  - ${{values.aws_environment_name}}-stage

variables:
  APP_SHORT_NAME: "${{ values.component_id }}"

include:
  - project: 'aad-admin/backstage-reference'
    ref: main 
    file:
      - 'common/cicd/.gitlab-ci-aws-base.yml'
      - 'common/cicd/.gitlab-ci-aws-iac-ecs.yml'
      - 'common/cicd/.gitlab-ci-aws-dind-spring-boot.yml'
