apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.component_id | dump }}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  tags:
    - aws
    - nodejs
    - eks
  iac-type: cdk
  annotations: 
    aws.amazon.com/baws-repo-secret-arn: ${{ values.aws_secret_repo_arn | dump }}
  links:
    - url: http://ALB_ENDPOINT
      title: Load Balancer Endpoint
      icon: info
  repo-secret-arn: ${{ values.aws_secret_repo_arn | dump }}
spec:
  type: aws-app
  owner: ${{ values.owner | dump }}
  lifecycle: experimental
  dependsOn: []

